Parameters:
  
  FileExchangeBucketName:
    Type: String
    
  ExchangableObjectsTTL:
    Type: Number
    Description: Time to live files in storage. In days
    Default: 1
    
  EmailSender:
    Description: "Verified SES E-Mail address"
    Type: String
 
  EmailRecipient: 
    Description: "Verified SES E-Mail address for the Sandbox or any other EMail for Normal mode"
    Type: String
    
  DeadLetterQueueAlarmTreshold:
    Description: "Length of DeadLetterQueue, which leads to rising a CloudWatch Alarm"
    Default: 5
    Type: Number
    
  LinkExpirationPeriod:
    Description: 'Seconds befor link to object expired'
    Default: 18000
    Type: Number
    
Resources:
  FileExchangeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Ref FileExchangeBucketName
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: 's3:ObjectCreated:*'
          Function: !GetAtt LinkGenerator.Arn
      LifecycleConfiguration:
        Rules:
        - Id: ObjectExpirationRule
          ExpirationInDays: !Ref ExchangableObjectsTTL
          Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref FileExchangeBucketLogs
        LogFilePrefix: _access_logs
          
  FileExchangeBucketLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:      
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${FileExchangeBucketName}-access-logs
      AccessControl: LogDeliveryWrite
      
  FileExchangeBucketLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref FileExchangeBucketLogs      
      PolicyDocument: 
        Statement: 
           - 
            Action:            
              - "s3:*"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${FileExchangeBucketName}-access-logs/*"
            Principal: 
              Service: "s3.amazonaws.com"
           - 
            Action: 
              - "s3:*"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${FileExchangeBucketName}-access-logs"
            Principal: 
              Service: "s3.amazonaws.com"
                       
  FileExchangeBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LinkGenerator
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:s3:::${FileExchangeBucketName}"          
    
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaCloudWatchLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: FileExchangeBucketPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:*'
              Resource: !Sub "arn:aws:s3:::${FileExchangeBucketName}/*"            
      - PolicyName: EmailSendingPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'SES:SendEmail'
                - 'SES:SendRawEmail'
                - 'SES:SendTemplatedEmail'
              Resource: !Sub 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*'
      - PolicyName: DeadLetterQueuePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'SQS:*'
              Resource: !GetAtt DeadLetterQueue.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      
  
  DeadLetterQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: "LinkGeneratorDeadLetterQueue"
  
  DeadLetterQueueDepthAlarm: 
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmDescription: "Alarm if queue depth grows beyond treshold"
      AlarmName: "DeadLetterQueueDepthAlarm"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions: 
        - 
          Name: "QueueName"
          Value: !GetAtt DeadLetterQueue.QueueName
      Statistic: "Sum"
      Period: "300"
      EvaluationPeriods: "1"
      Threshold: !Ref DeadLetterQueueAlarmTreshold
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions: 
        - !ImportValue CommonAlarmTopic
      InsufficientDataActions: 
        - !ImportValue CommonAlarmTopic
  
  LinkGenerator: 
    Type: "AWS::Lambda::Function"
    Properties: 
      FunctionName: "LinkGenerator"
      Handler: "index.lambda_generator_handler"        
      Role: !GetAtt LambdaExecutionRole.Arn
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          EmailRecipient: !Ref EmailRecipient
          EmailSender: !Ref EmailSender
          LinkExpirationPeriod: !Ref LinkExpirationPeriod
          EmailConfigurationSetName: !ImportValue ConfigSetName
          EmailTemplateLinkName: !ImportValue LinkDownloadTemplateName
      Code:
        ZipFile: !Sub |
            import logging
            import json
            import boto3
            import os
          
            from botocore.exceptions import ClientError
            from botocore.client import Config
          
            logger = logging.getLogger()
            logger.setLevel(logging.INFO)
          
            s3 = boto3.client('s3', config=Config(signature_version='s3v4'))
            ses_client = boto3.client('ses',region_name='${AWS::Region}')

            def lambda_generator_handler(event, context):
              
                bucket_name = event['Records'][0]['s3']['bucket']['name']              
                file_name = event['Records'][0]['s3']['object']['key']                  
                            
                link = s3.generate_presigned_url(
                  ClientMethod='get_object',
                    Params={
                     'Bucket': bucket_name,
                     'Key': file_name
                  },
                  ExpiresIn=os.environ['LinkExpirationPeriod'] 
                ) 

                recipient = os.environ['EmailRecipient'] 
                sender = os.environ['EmailSender'] 
                
                template_data = '{ \"LINK\":\"REPLACEMENT_LINK\" }'.replace('REPLACEMENT_LINK', link)
                
                logger.info('Template link is {}'.format(link)) 
              
                #TODO Read response    
                response = ses_client.send_templated_email(
                  Destination={
                      'ToAddresses': [ recipient ],
                  },                   
                  Template=os.environ['EmailTemplateLinkName'],
                  TemplateData = template_data,
                  Source = sender,
                  ConfigurationSetName=os.environ['EmailConfigurationSetName'],
                )
              
                return {
                    'statusCode': 200,
                    'body': json.dumps('S3 Lambda sender invoked')
                }
      Runtime: "python3.6"
      Timeout: 25
      TracingConfig:
        Mode: "Active"
        
