#TODO: Add SNS notificator

Parameters:
    
  ConfigSetName:
    Description: Name of configuration set
    Default: MainSender
    Type: String
    
  LinkDownloadTemplateName:
    Description: "Name of E-Mail template for sending link"
    Default: "LinkDownloadTemplate"
    Type: String
  
  AdminAlarmEMail:
    Description: 'EMail for sending alarms'
    Type: String
  
Resources:

  CommonAlarmTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "CommonAlarmNotification" 
      TopicName: "CommonAlarmNotification"
      Subscription: 
        - 
          Endpoint: !Ref AdminAlarmEMail
          Protocol: "email"  

  ConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Ref ConfigSetName
  
  LinkTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: !Ref LinkDownloadTemplateName
        SubjectPart: "EMail from link generator"
        TextPart: "Link to <a href='{{LINK}}'>download</a>"
        HtmlPart: | 
               "<html>
                  <head></head>
                  <body>
                    <h1>Link generator</h1>
                    <p>Link to <a href='{{LINK}}'>download</a></p>
                  </body>
               </html>"
  
Outputs:
  
  CommonAlarmTopic:
    Value: !Ref CommonAlarmTopic 
    Export:
      Name: "CommonAlarmTopic"
  
  ConfigSetName:
    Value: !Ref ConfigSetName
    Export:
      Name: ConfigSetName
  
  LinkDownloadTemplateName:
    Value: !Ref LinkDownloadTemplateName
    Export:
      Name: LinkDownloadTemplateName    
      
  