#TODO: Add SNS notificator

Parameters:
    
  ConfigSetName:
    Description: Name of configuration set
    Default: MainSender
    Type: String
    
  LinkDownloadTemplateName:
    Description: "Name of E-Mail template for sending link"
    Default: "LinkDownloadTemplate"
    Type: String
  
  AdminAlarmEMail:
    Description: 'EMail for sending alarms'
    Default: alexandresenko@gmail.com
    Type: String
  
Resources:

  CommonAlarmTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "CommonAlarmNotification" 
      TopicName: "CommonAlarmNotification"
      Subscription: 
        - 
          Endpoint: !Ref AdminAlarmEMail
          Protocol: "email"  

  ConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Ref ConfigSetName
  
  LinkTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: !Ref LinkDownloadTemplateName
        SubjectPart: "EMail from link generator"
        TextPart: "Link to <a href='{{LINK}}'>download</a>"
        HtmlPart: | 
               "<html>
                  <head></head>
                  <body>
                    <h1>Link generator</h1>
                    <p>Link to <a href='{{LINK}}'>download</a></p>
                  </body>
               </html>"
                          
      

  # TODO: 
  # https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-ses-configurationseteventdestination.html  
  #EmailsSendingLogs:
  #  Type: AWS::SES::ConfigurationSetEventDestination
  #  Properties:
  #    ConfigurationSetName: !Ref ConfigSet
  #    EventDestination:
  #      Name: !Ref EventDestinationName
  #      Enabled: true
  #      MatchingEventTypes:
  #        - !Ref EventType1
  #        - !Ref EventType2
  #        - !Ref EventType3
  #      CloudWatchDestination:
  #        DimensionConfigurations:
  #          - DimensionName: !Ref DimensionName1
  #            DimensionValueSource: !Ref DimensionValueSource1
  #            DefaultDimensionValue: !Ref DefaultDimensionValue1
  #          - DimensionName: !Ref DimensionName2
  #            DimensionValueSource: !Ref DimensionValueSource2
  #            DefaultDimensionValue: !Ref DefaultDimensionValue2
  
Outputs:
  
  CommonAlarmTopic:
    Value: !Ref CommonAlarmTopic 
    Export:
      Name: "CommonAlarmTopic"
  
  ConfigSetName:
    Value: !Ref ConfigSetName
    Export:
      Name: ConfigSetName
  
  LinkDownloadTemplateName:
    Value: !Ref LinkDownloadTemplateName
    Export:
      Name: LinkDownloadTemplateName    
      
  