# TODO: Add cloudwatch alarm
# TODO: Add export name

Parameters:
  
  ReadCapacityUnitsMin:
    Type: Number
    Default: 4
    
  ReadCapacityUnitsMax:
    Type: Number
    Default: 15
    
  WriteCapacityUnitsMin:
    Type: Number
    Default: 4
    
  WriteCapacityUnitsMax:
    Type: Number
    Default: 15
    
Resources:
  CustomerMetadata:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "CustomerMetadata"
      AttributeDefinitions:
        -
          AttributeName: "EMail"
          AttributeType: "S"
        -
          AttributeName: "Filename"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "EMail"
          KeyType: "HASH"
        -
          AttributeName: "Filename"
          KeyType: "RANGE"      
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnitsMin
        WriteCapacityUnits: !Ref WriteCapacityUnitsMin
  ReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref ReadCapacityUnitsMax
      MinCapacity: !Ref ReadCapacityUnitsMin
      ResourceId: !Join
        - /
        - - table
          - !Ref CustomerMetadata
      RoleARN: !GetAtt CustomerMetadataScalingRole.Arn
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb  
  WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref WriteCapacityUnitsMax
      MinCapacity: !Ref WriteCapacityUnitsMin
      ResourceId: !Join
        - /
        - - table
          - !Ref CustomerMetadata
      RoleARN: !GetAtt CustomerMetadataScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  CustomerMetadataScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"
  ReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization  
  WriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization