#TODO: Add access logs to "FileExchangeBucket"
Parameters:
  
  RootDomainName:
    Type: String
    Default: "alexandrecabdidate.se"
  
Resources:

  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub "${RootDomainName}-lambda-code"
      
  FileExchangeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub "${RootDomainName}-file-exchange"
      
Outputs:
  
  LambdaCodeBucket:
    Value: !Ref LambdaCodeBucket
    Export:
      Name: LambdaCodeBucket
   
  FileExchangeBucket:
    Value: !Ref FileExchangeBucket
    Export:
      Name: FileExchangeBucket
  